#!/usr/bin/env php
<?php

use App\Kernel;
use Symfony\Bundle\FrameworkBundle\Console\Application;

/**
 * --------------------------------
 *  Bob "The builder"
 * --------------------------------
 * 
 * This is an abstracion on symfony's php bin/console with
 * extra commands.
 * 
 */

if (!is_file(__DIR__.'/vendor/autoload_runtime.php')) {
    throw new LogicException('Symfony Runtime is missing. Try running "composer require symfony/runtime".');
}

require_once __DIR__.'/vendor/autoload_runtime.php';

return function (array $context) {
    $kernel = new Kernel($context['APP_ENV'], (bool) $context['APP_DEBUG']);

    return new Application($kernel);
};